spring:
  application:
    name: login-starter
  redis:
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 5000
    password: password
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    username: root
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=true&serverTimezone=Asia/Shanghai
    hikari:
      max-lifetime: 1000000

# mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

login:
  no-need: /user/**,/test/helloWorld

shiro:
  loginUrl: 404.html