// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: samples_api.proto

package org.apache.dubbo.greet;

public final class Greet {
  private Greet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021samples_api.proto\022\003api\"\034\n\014HelloRequest" +
      "\022\014\n\004name\030\001 \001(\t\"-\n\004User\022\014\n\004name\030\001 \001(\t\022\n\n\002" +
      "id\030\002 \001(\t\022\013\n\003age\030\003 \001(\0052k\n\007Greeter\022*\n\010SayH" +
      "ello\022\021.api.HelloRequest\032\t.api.User\"\000\0224\n\016" +
      "SayHelloStream\022\021.api.HelloRequest\032\t.api." +
      "User\"\000(\0010\001B4\n\026org.apache.dubbo.greetB\005Gr" +
      "eetP\001Z\013./greet;api\242\002\003HLWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_api_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_api_User_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_User_descriptor,
        new java.lang.String[] { "Name", "Id", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
