// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: samples_api.proto

package org.apache.dubbo.greet;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
